### ISSUE TITLE
[Bug] Error when specifying testing gpu_id

### ISSUE THREAD

**Issue by Lotayou** [open-mmlab/mmfashion#20]
When I try to run multiple evaluations I would want them to run on dfferent gpus, to this end, I changed the respective configuration files, 

```
gpus = dict(train=[0, 1, 2, 3], test=[1])
```

However I encountered the following error:
```
load checkpoint from: checkpoints/retrieval_clothes_resnet50/epoch_150.pth                            │+-----------------------------------------------------------------------------+
Traceback (most recent call last):                                                                    │| Processes:                                                       GPU Memory |
  File "tools/test_retriever.py", line 88, in <module>                                                │|  GPU       PID   Type   Process name                             Usage      |
    main()                                                                                            │|=============================================================================|
  File "tools/test_retriever.py", line 84, in main                                                    │|    0      1327      G   /usr/lib/xorg/Xorg                            18MiB |
    logger=logger)                                                                                    │|    0      1360      G   /usr/bin/gnome-shell                          49MiB |
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│|    0      1541      G   /usr/lib/xorg/Xorg                           190MiB |
.7.egg/mmfashion/apis/test_retriever.py", line 40, in test_retriever                                  │|    0      1670      G   /usr/bin/gnome-shell                         262MiB |
    _non_dist_test(model, query_set, gallery_set, cfg, validate=validate)                             │|    0     12106      C   python                                      2871MiB |
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│+-----------------------------------------------------------------------------+
.7.egg/mmfashion/apis/test_retriever.py", line 74, in _non_dist_test                                  │                                                                                                     
    query_embeds = _process_embeds(query_set, model, cfg)                                             │                                                                                                     
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│                                                                                                     
.7.egg/mmfashion/apis/test_retriever.py", line 61, in _process_embeds                                 │                                                                                                     
    embed = model(data['img'], data['landmark'], return_loss=False)                                   │                                                                                                     
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/torch/nn/modules/module.py"│                                                                                                     
, line 541, in __call__                                                                               │                                                                                                     
    result = self.forward(*input, **kwargs)                                                           │                                                                                                     
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/torch/nn/parallel/data_para│                                                                                                     
llel.py", line 146, in forward                                                                        │                                                                                                     
    "them on device: {}".format(self.src_device_obj, t.device))                                       │                                                                                                     
RuntimeError: module must have its parameters and buffers on device cuda:1 (device_ids[0]) but found o│                                                                                                     
ne of them on device: cuda:0             
```

It seems that there's something in the core module that by default load tensors into gpu 0, maybe some thing like `x = x.cuda(0)`? Hope this problem can be fixed later. Thanks!

**Comment by Lotayou** [comment]
@veralauee I solved the problem but couldn't submit a PR since I'm interning now. You can fix it yourself, shouldn't be too hard
### Workaround and Bug location
I removed the MMDataParallel wrapper in model creation, now it becomes:
```
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│|    0     12106      C   python                                      2871MiB |                      
.7.egg/mmfashion/apis/test_retriever.py", line 66, in _process_embeds                                 │+-----------------------------------------------------------------------------+                      
    embed = model(img, lmk, return_loss=False)                                                        │                                                                                                     
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/torch/nn/modules/module.py"├─────────────────────────────────────────────────────────────────────────────────────────────────────
, line 541, in __call__                                                                               │
    result = self.forward(*input, **kwargs)                                                           │Using /home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│Searching for chardet==3.0.4
.7.egg/mmfashion/models/retriever/base.py", line 58, in forward                                       │Best match: chardet 3.0.4
    return self.forward_test(img, landmark)                                                           │Adding chardet 3.0.4 to easy-install.pth file
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│Installing chardetect script to /home/lingbo.ylb/anaconda3/envs/lingbo/bin
.7.egg/mmfashion/models/retriever/base.py", line 34, in forward_test                                  │
    return self.aug_test(imgs, landmarks)                                                             │Using /home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│Searching for urllib3==1.25.7
.7.egg/mmfashion/models/retriever/roi_retriever.py", line 104, in aug_test                            │Best match: urllib3 1.25.7
    feat = self.extract_feat(x, landmarks)                                                            │Adding urllib3 1.25.7 to easy-install.pth file
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│
.7.egg/mmfashion/models/retriever/roi_retriever.py", line 48, in extract_feat                         │Using /home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages
    local_x = self.roi_pool(x, landmarks)                                                             │Searching for certifi==2019.11.28
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/torch/nn/modules/module.py"│Best match: certifi 2019.11.28
, line 541, in __call__                                                                               │Adding certifi 2019.11.28 to easy-install.pth file
    result = self.forward(*input, **kwargs)                                                           │
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/mmfashion-0.1.0+7a5acde-py3│Using /home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages
.7.egg/mmfashion/models/roi_pool/roi_pooling.py", line 70, in forward                                 │Searching for setuptools==42.0.2.post20191203
    padding_mode='border')                                                                            │Best match: setuptools 42.0.2.post20191203
  File "/home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages/torch/nn/functional.py", li│Adding setuptools 42.0.2.post20191203 to easy-install.pth file
ne 2698, in grid_sample                                                                               │Installing easy_install script to /home/lingbo.ylb/anaconda3/envs/lingbo/bin
    return torch.grid_sampler(input, grid, mode_enum, padding_mode_enum, align_corners)               │
RuntimeError: grid_sampler(): expected input and grid to be on same device, but input is on cuda:1 and│Using /home/lingbo.ylb/anaconda3/envs/lingbo/lib/python3.7/site-packages
 grid is on cuda:0                                                                                    │Finished processing dependencies for mmfashion==0.1.0+7a5acde
```

And by checking the `mmfashion/models/roi_pool/roi_pooling.py`, I found the line causing error would be 
```

        ab = [np.array([[self.a, 0], [0, self.b]]) for _ in range(batch_size)]
        ab = np.stack(ab, axis=0)
        ab = torch.from_numpy(ab).float().cuda()    # Warning: Here ab is assigned to cuda:0
        size = torch.Size((batch_size, features.size(1), self.roi_size,
                           self.roi_size))

        pooled = []
        for l in range(self.num_lms):
            tx = -1 + 2 * landmarks[:, l, 0] / float(self.crop_size)
            ty = -1 + 2 * landmarks[:, l, 1] / float(self.crop_size)
            t_xy = torch.stack((tx, ty)).view(batch_size, 2, 1)
            theta = torch.cat((ab, t_xy), 2)   # now theta is also on cuda:0

            flowfield = nn.functional.affine_grid(theta, size)   # and this affects flowfield.
            flowfield = flowfield.to(torch.float32)
```

### Fix
Write this line somewhere before extracing embeddings
```
torch.cuda.set_device(cfg.gpus.test[0])
```
