### ISSUE TITLE
An error of the test of LandmarkDetector

### ISSUE THREAD

**Issue by WCZ93762** [open-mmlab/mmfashion#25]
When I ran the 
` python tools/test_landmark_detector.py --config configs/landmark_detect/landmark_detect_vgg.py --checkpoint checkpoint/LandmarkDetect/vgg/global/latest.pth ` ,
it occured:

Traceback (most recent call last):
  File "tools/test_landmark_detector.py", line 84, in <module>
    main()
  File "tools/test_landmark_detector.py", line 80, in main
    logger=logger)
  File "/home/user03/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmfashion/apis/test_landmark_detector.py", line 36, in test_landmark_detector
    _non_dist_test(model, dataset, cfg, validate=validate)
  File "/home/user03/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmfashion/apis/test_landmark_detector.py", line 63, in _non_dist_test
    pred_vis, pred_lm, vis, landmark)
  File "/home/user03/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmfashion/core/evaluation/landmark_detect_eval.py", line 95, in evaluate_landmark_detection
    vis * pred_lm_np, vis * landmark_np)
  File "/home/user03/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmfashion/core/evaluation/landmark_detect_eval.py", line 32, in compute_distance
    if self.demo:
AttributeError: 'LandmarkDetectorEvaluator' object has no attribute 'demo'

 How can I solve this problem? Thank you!

**Comment by veralauee** [comment]
Sorry about the conflict setting after updating the landmark detection demo codes. I just corrected the codes of landmark evaluator, now you can pull it and re-try.

**Comment by liuziwei7** [comment]
Will close this issue for now. Please feel free to re-open it in case of any further questions.
