### ISSUE TITLE
Can't load fashion segmentation model

### ISSUE THREAD

**Issue by GrininViktor** [open-mmlab/mmfashion#54]
Hi! Could you help me with my issue?
I have downloaded epoch_15.pth for fashion segmentation from Model_Zoo, but init_detector returns "The model and loaded state dict do not match exactly" for all mask_rsnn configs. Where can I get a suitable one?

**Comment by veralauee** [comment]
Would you please paste your error information? Not very clear about the cause.

**Comment by GrininViktor** [comment]
I have downloaded docker with mmdetection and copied the necessary files to the docker following fashion_parsing_segmentation/README.md. And I have this error

root@9a3f75b44f42:/mmdetection# python tools/demo.py 
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
None
Traceback (most recent call last):
  File "tools/demo.py", line 23, in <module>
    main()
  File "tools/demo.py", line 12, in main
    model = init_detector(config, checkpoint, device='cuda:0')
  File "/mmdetection/mmdet/apis/inference.py", line 34, in init_detector
    model = build_detector(config.model, test_cfg=config.test_cfg)
  File "/mmdetection/mmdet/models/builder.py", line 48, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/mmdetection/mmdet/models/builder.py", line 20, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'bbox_roi_extractor'

**Comment by furkanpur** [comment]
Same here.

**Comment by sYeaLumin** [comment]
Same here.

It seems that the demo use old config file.
https://github.com/open-mmlab/mmdetection/issues/2807

After updating config file, it still doesn't work.

mmdetection # python3 tools/demo.py --checkpoint checkpoints/seg_epoch_15_fixed.pth --config configs/mmfashion/mask_rcnn_r50_fpn_1x_fixed.py
Namespace(checkpoint='checkpoints/seg_epoch_15_fixed.pth', config='configs/mmfashion/mask_rcnn_r50_fpn_1x_fixed.py', input='demo/01_4_full.jpg')
Traceback (most recent call last):
  File "tools/demo.py", line 57, in <module>
    main()
  File "tools/demo.py", line 41, in main
    result = inference_detector(model, img)
  File "/lumin/mmfashion/mmdetection/mmdet/apis/inference.py", line 85, in inference_detector
    result = model(return_loss=False, rescale=True, **data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/lumin/mmfashion/mmdetection/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/lumin/mmfashion/mmdetection/mmdet/models/detectors/base.py", line 150, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/lumin/mmfashion/mmdetection/mmdet/models/detectors/base.py", line 131, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/lumin/mmfashion/mmdetection/mmdet/models/detectors/two_stage.py", line 192, in simple_test
    x, proposal_list, img_metas, rescale=rescale)
  File "/lumin/mmfashion/mmdetection/mmdet/models/roi_heads/standard_roi_head.py", line 245, in simple_test
    x, img_metas, proposal_list, self.test_cfg, rescale=rescale)
  File "/lumin/mmfashion/mmdetection/mmdet/models/roi_heads/test_mixins.py", line 70, in simple_test_bboxes
    cfg=rcnn_test_cfg)
  File "/lumin/mmfashion/mmdetection/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/lumin/mmfashion/mmdetection/mmdet/models/roi_heads/bbox_heads/bbox_head.py", line 223, in get_bboxes
    cfg.max_per_img)
  File "/lumin/mmfashion/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 42, in multiclass_nms
    bboxes = bboxes[valid_mask]
IndexError: The shape of the mask [1000, 80] at index 1 does not match the shape of the indexed tensor [1000, 81, 4] at index 1

**Comment by Hanv2** [comment]
you should download the mmdection of version 1.2，not 2.0

**Comment by veralauee** [comment]
Yes. We use mmdetection v1.2. When we wrote this detection module, mmdetection was not upgraded to 2.0

**Comment by jis3613** [comment]
Could you tell me how to install 1.2 version of mmdetection?

**Comment by Hanv2** [comment]
> Could you tell me how to install 1.2 version of mmdetection?

https://github.com/open-mmlab/mmdetection/releases/tag/v1.2.0,here.

**Comment by Hanv2** [comment]
> Could you tell me how to install 1.2 version of mmdetection?

check this link
https://github.com/open-mmlab/mmdetection/releases/tag/v1.2.0

**Comment by jis3613** [comment]
> > Could you tell me how to install 1.2 version of mmdetection?
> 
> check this link
> https://github.com/open-mmlab/mmdetection/releases/tag/v1.2.0

Thank you!

**Comment by kartikwar** [comment]
I tried using mmdetection version 1.2 as well. But getting the same issue init() got an unexpected keyword argument 'bbox_roi_extractor'

**Comment by kartikwar** [comment]
I used the source code for version 1.2 for mmdetection and now I am getting the error No module named 'mmcv.cnn.weight_init' . My mmcv version is :- mmcv==1.0.4

Other versions:

cuda==10.0
pytorch==1.4.0

**Comment by kartikwar** [comment]
Anyone else facing the same issue can update their mmcv version to mmcv==0.5.1. This fixed the issue for me.

**Comment by ousinkou** [comment]
> Yes. We use mmdetection v1.2. When we wrote this detection module, mmdetection was not upgraded to 2.0

Is there any plan to update the mmdetection version to 2.x?
