### ISSUE TITLE
Recommendation Test AssertionError

### ISSUE THREAD

**Issue by DaniellePerri1** [open-mmlab/mmfashion#65]
Hi, 
First thanks for sharing this repo!

I've followed GETTING_STARTED.md, and tried to run the fashion-compatibility predictor on Polyvore dataset as instructed (**Test a dataset** section, 4'th task):
`python tools/test_fashion_recommender.py \
    --config configs/fashion_recommendation/type_aware_recommendation_polyvore_disjoint.py
    --checkpoint checkpoint/FashionRecommend/TypeAware/latest.pth`

But I got the following error:

 2020-06-05 15:24:36,526 - INFO - Distributed test: False
dataset loaded
Traceback (most recent call last):
  File "./tools/test_fashion_recommender.py", line 71, in <module>
    main()
  File "./tools/test_fashion_recommender.py", line 62, in main
    model = build_fashion_recommender(cfg.model)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 99, in build_fashion_recommender
    return build(cfg, RECOMMENDER)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 35, in build
    return _build_module(cfg, registry, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 27, in _build_module
    return obj_type(**args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/fashion_recommender/type_aware_recommend.py", line 22, in __init__
    type_specific_net)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 91, in build_type_specific_net
    return build(cfg, TYPESPECIFICNET)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 35, in build
    return _build_module(cfg, registry, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 27, in _build_module
    return obj_type(**args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/type_specific_net/type_specific_net.py", line 63, in __init__
    ), "learn a metric or use fc layer to transform the general embeddings, only one can be true."  # noqa
AssertionError: learn a metric or use fc layer to transform the general embeddings, only one can be true.

**Do you guys have any idea what I'm doing wrong?**

For the checkpoint I used https://drive.google.com/file/d/1T-9BLWbuZhEHpX8xV6f1ZoGUpcjV3efc/view pretrained model, and changed its name to latest.pth to match the name in the command.

Thanks In advance!

**Comment by veralauee** [comment]
I have updated the config file just now. Please pull it and re-try.
Specifically, in this config file, "learned" means learning a metric to transform the general embeddings to the type-specific space, "use_fc" means using a fully-connected layer to transform the general embeddings to the type-specific space. Only one of them can be true, the other one must be false.

**Comment by DaniellePerri1** [comment]
Hi thanks for the quick reply, but I got a following error:
  File "./tools/test_fashion_recommender.py", line 71, in <module>
    main()
  File "./tools/test_fashion_recommender.py", line 62, in main
    model = build_fashion_recommender(cfg.model)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 99, in build_fashion_recommender
    return build(cfg, RECOMMENDER)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 35, in build
    return _build_module(cfg, registry, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 27, in _build_module
    return obj_type(**args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/fashion_recommender/type_aware_recommend.py", line 23, in __init__
    self.triplet_net = builder.build_triplet_net(triplet_net)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 95, in build_triplet_net
    return build(cfg, TRIPLETNET)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 35, in build
    return _build_module(cfg, registry, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 27, in _build_module
    return obj_type(**args)
TypeError: __init__() got an unexpected keyword argument 'loss_sim'

**Any idea?**

**Comment by veralauee** [comment]
We just updated the codes in fashion recommendation task. Please pull the codes and try again.

**Comment by veralauee** [comment]
Close it since no further comments.
