### ISSUE TITLE
OSError: checkpoint/vgg16.pth is not a checkpoint file (LANDMARK DETECTION)

### ISSUE THREAD

**Issue by Akella17** [open-mmlab/mmfashion#68]
I need to obtain the fashion landmarks present in a clothing image. I was trying to use the pre-trained fashion landmark detector by running the following:
```
python demo/test_landmark_detector.py --input demo/imgs/04_1_front.jpg --checkpoint checkpoints/latest.pth --config configs/landmark_detect/landmark_detect_vgg.py
```
(I have downloaded the ```vgg.pth``` and ```latest.pth``` files to ```checkpoints/```) but I get the following error:
```
Traceback (most recent call last):
  File "demo/test_landmark_detector.py", line 72, in <module>
    main()
  File "demo/test_landmark_detector.py", line 52, in main
    model = build_landmark_detector(cfg.model)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 75, in build_landmark_detector
    return build(cfg, LANDMARKDETECTOR)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 35, in build
    return _build_module(cfg, registry, default_args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/builder.py", line 27, in _build_module
    return obj_type(**args)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/landmark_detector/landmark_detector.py", line 29, in __init__
    self.init_weights(pretrained=pretrained)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/landmark_detector/landmark_detector.py", line 73, in init_weights
    self.backbone.init_weights(pretrained=pretrained)
  File "/usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/backbones/vgg.py", line 53, in init_weights
    load_checkpoint(self, pretrained)
  File "/usr/local/lib/python3.6/dist-packages/mmcv-0.5.9-py3.6-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 218, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location)
  File "/usr/local/lib/python3.6/dist-packages/mmcv-0.5.9-py3.6-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 193, in _load_checkpoint
    raise IOError(f'{filename} is not a checkpoint file')
OSError: checkpoint/vgg16.pth is not a checkpoint file
```

**Comment by peyyman** [comment]
I have the same issue, any solution?

**Comment by AaradhyaSaxena** [comment]
how did you fix it?

**Comment by BitnaKeum** [comment]
Have you solved this problem? I am struggling with the same error.

**Comment by Lytua** [comment]
Have you solved this problem?

**Comment by sinanmut** [comment]
I am having the same issue, is there any solution for it?

**Comment by ytk1216** [comment]
i try it with 

python demo/test_attr_predictor.py --input demo/imgs/attr_pred_demo1.jpg

raise IOError(f'{filename} is not a checkpoint file')
OSError: checkpoint/Predict/vgg/global/latest.pth is not a checkpoint file

**Comment by NaumanHSA** [comment]
The folder specified in the config file is 'checkpoint' but your folder is 'checkpoints'. Please make sure you either change the path in the config file or simply rename your folder.
