### ISSUE TITLE
Error running the test code

### ISSUE THREAD

**Issue by NoTrump** [open-mmlab/mmfashion#73]
The environment was configured according to the process in the document, and the test code was run incorrectly. What is the reason?

(base) F:\mmfashion>python demo/test_predictor.py --input demo/imgs/attr_pred_demo1.jpg
Traceback (most recent call last):
  File "demo/test_predictor.py", line 57, in <module>
    main()
  File "demo/test_predictor.py", line 37, in main
    cfg = Config.fromfile(args.config)
  File "E:\anaconda3\lib\site-packages\mmcv\utils\config.py", line 178, in fromfile
    cfg_dict, cfg_text = Config._file2dict(filename)
  File "E:\anaconda3\lib\site-packages\mmcv\utils\config.py", line 104, in _file2dict
    osp.join(temp_config_dir, temp_config_name))
  File "E:\anaconda3\lib\shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\MyPC\\AppData\\Local\\Temp\\tmp4d6lsncl\\tmpm5vzrhwx.py'

**Comment by maithil22** [comment]
I am facing the same issue. Is the problem solved?

**Comment by vitowzy** [comment]
That's the question I'm struggling with.
