### ISSUE TITLE
No module named 'mmcv.cnn.weight_init' 

### ISSUE THREAD

**Issue by jis3613** [open-mmlab/mmfashion#74]
1.
Hi, I am trying to run the demo of fashion segmentation, but I get the error below.
I installed mmcv with 
''' pip install mmcv '''
so I have mmcv in my environment.
Maybe I have to use different version of mmcv?
I am currently using mmcv 0.6.2

2.
I saw another issue saying that I should download the mmdection of version 1.2，not 2.0 .
Could you let me know how to do that?
One thing I did is to go to '/mmdetection' and run '''python setup.py develop'''

[The error message]
~ $ python mmdetection/tools/demo.py --configs configs/fashion_parsing_segmentation/mask_rcnn_r50_fpn_1x.py
Traceback (most recent call last):
  File "mmdetection/tools/demo.py", line 3, in <module>
    from mmdet.apis import inference_detector, init_detector, show_result
  File "/workspace/fashion-seg/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
  File "/workspace/fashion-seg/mmdetection/mmdet/apis/inference.py", line 12, in <module>
    from mmdet.models import build_detector
  File "/workspace/fashion-seg/mmdetection/mmdet/models/__init__.py", line 3, in <module>
    from .bbox_heads import *  # noqa: F401,F403
  File "/workspace/fashion-seg/mmdetection/mmdet/models/bbox_heads/__init__.py", line 3, in <module>
    from .double_bbox_head import DoubleConvFCBBoxHead
  File "/workspace/fashion-seg/mmdetection/mmdet/models/bbox_heads/double_bbox_head.py", line 2, in <module>
    from mmcv.cnn.weight_init import normal_init, xavier_init
ModuleNotFoundError: No module named 'mmcv.cnn.weight_init'

**Comment by jis3613** [comment]
I downgraded the version of MMCV and it is fixed now
