### ISSUE TITLE
"python setup.py install" not working

### ISSUE THREAD

**Issue by fuddyduddy** [open-mmlab/mmfashion#80]
I run the command to install mmfashion module. However, my pytorch version is 1.2.0.
```
pytorch                   1.2.0           py3.7_cuda100_cudnn7_1    pytorch
```
I read the pytorch website, since i am windows 10, thus it seems i can't download its 1.5.1 version. It there anyway i can work around this?? Thanks.

```
ERROR: Could not find a version that satisfies the requirement torch>=1.3 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.3
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "C:\Users\user\anaconda3\envs\FTDS\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\user\\anaconda3\\envs\\FTDS\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp0wjyz_4b', '--quiet', 'torch>=1.3']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 139, in <module>
    zip_safe=False)
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\setuptools\__init__.py", line 143, in setup
    _install_setup_requires(attrs)
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\setuptools\__init__.py", line 138, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\setuptools\dist.py", line 698, in fetch_build_eggs
    replace_conflicting=True,
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\pkg_resources\__init__.py", line 783, in resolve
    replace_conflicting=replace_conflicting
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\pkg_resources\__init__.py", line 1066, in best_match
    return self.obtain(req, installer)
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\pkg_resources\__init__.py", line 1078, in obtain
    return installer(requirement)
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\setuptools\dist.py", line 754, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "C:\Users\user\anaconda3\envs\FTDS\lib\site-packages\setuptools\installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['C:\\Users\\user\\anaconda3\\envs\\FTDS\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\user\\AppData\\Local\\Temp\\tmp0wjyz_4b', '--quiet', 'torch>=1.3']' returned non-zero exit status 1.
```

**Comment by veralauee** [comment]
It might be the version mismatch. Not very clear about this case.

**Comment by veralauee** [comment]
Closed since no activity
