### ISSUE TITLE
Fine attribute predictor landmark pooling gives invalid input size

### ISSUE THREAD

**Issue by hinneslung** [open-mmlab/mmfashion#87]
I am using the recently added more accurate attribute predictor with landmark pooling. I placed the downloaded model in checkpoint/landmark/resnet50.pth, and a backbone resnet50 model in checkpoint/resnet50.pth, and run the below command:

```bash
python demo/test_cate_attr_predictor.py --input demo/imgs/attr_pred_demo2.jpg  --checkpoint checkpoint/landmark/resnet50.pth --config ./configs/category_attribute_predict/roi_predictor_resnet.py
`````

And got the error:

```bash
pretrained model checkpoint/resnet50.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

model loaded from checkpoint/landmark/resnet50.pth
Traceback (most recent call last):
  File "demo/test_cate_attr_predictor.py", line 65, in <module>
    main()
  File "demo/test_cate_attr_predictor.py", line 55, in main
    attr_prob, cate_prob = model(img_tensor, attr=None,
  File "/home/user/.pyenv/versions/mmfashion-3.8.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.pyenv/versions/mmfashion-3.8.3/lib/python3.8/site-packages/mmfashion-0.4.0-py3.8.egg/mmfashion/models/predictor/base.py", line 41, in forward
    return self.forward_test(img, landmark)
  File "/home/user/.pyenv/versions/mmfashion-3.8.3/lib/python3.8/site-packages/mmfashion-0.4.0-py3.8.egg/mmfashion/models/predictor/base.py", line 29, in forward_test
    return self.simple_test(img[0], landmark[0])
  File "/home/user/.pyenv/versions/mmfashion-3.8.3/lib/python3.8/site-packages/mmfashion-0.4.0-py3.8.egg/mmfashion/models/predictor/roi_attr_cate_predictor.py", line 56, in simple_test
    attr_pred, cate_pred = self.aug_test(x, landmark)
  File "/home/user/.pyenv/versions/mmfashion-3.8.3/lib/python3.8/site-packages/mmfashion-0.4.0-py3.8.egg/mmfashion/models/predictor/roi_attr_cate_predictor.py", line 64, in aug_test
    local_x = self.roi_pool(x, landmark)
  File "/home/user/.pyenv/versions/mmfashion-3.8.3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.pyenv/versions/mmfashion-3.8.3/lib/python3.8/site-packages/mmfashion-0.4.0-py3.8.egg/mmfashion/models/roi_pool/roi_pooling.py", line 51, in forward
    landmarks = landmarks.view(batch_size, self.num_lms, 2)
RuntimeError: shape '[1, 8, 2]' is invalid for input of size 1
```

**Comment by veralauee** [comment]
The pretrained checkpoint `--checkpoint checkpoint/landmark/resnet50.pth ` you used is wrong. This is the model to do landmark prediction, not the model to do category and attribute prediction. Please download the right one from the Model Zoo.

**Comment by hinneslung** [comment]
Would you mind reviewing the links in model zoo md? I am downloading  https://drive.google.com/file/d/1zsgxJAkdumpw4uDkapb1Ulq-aG1Hwz45/view?usp=sharing shown under https://github.com/open-mmlab/mmfashion/blob/master/docs/MODEL_ZOO.md#category-and-attribute-predictionfine

**Comment by Lytua** [comment]
I got same problem.....

**Comment by zyue1105** [comment]
you can change the landmark size to [1, 8, 2] to get the code run https://github.com/open-mmlab/mmfashion/blob/master/demo/test_cate_attr_predictor.py#L44, but that won't give you a good result since the landmark is missing.

my understanding is the demo code needs to first predict landmark https://github.com/open-mmlab/mmfashion/issues/120

**Comment by JihyeJung-Work** [comment]
> The pretrained checkpoint `--checkpoint checkpoint/landmark/resnet50.pth ` you used is wrong. This is the model to do landmark prediction, not the model to do category and attribute prediction. Please download the right one from the Model Zoo.

I have downloaded the right checkpoint file, but occurs the same error.
