### ISSUE TITLE
Quick start for making inference (e.g., attribute prediction, landmark detection) on an image?

### ISSUE THREAD

**Issue by gyang274** [open-mmlab/mmfashion#9]
Try to input an image and make inference (attributes/landmark) on an image using the pre-tained model.

Downloaded and installed the package
```
git clone https://github.com/open-mmlab/mmfashion.git
cd mmfashion
python setup.py install
```

Downloaded the pre-trained model checkpoint for attribute prediction, try to run some inference.

**Q1**: have to create a set of **empty** file **data/Attr_Predict/Anno/test\*.txt** to run.

We should not be supposed to know the attribute when makes prediction on an unseen image, right? I guess the test here is testing, instead of inferencing?
```
mmfashion$ tree data
data
├── Attr_Predict
│   ├── Anno
│   │   ├── test_attr.txt
│   │   ├── test_bbox.txt
│   │   ├── test_cate.txt
│   │   ├── test_landmarks.txt
│   │   └── test.txt
│   └── Img
│       └── 11006215.jpg
├── prepare_attr_pred.py
├── prepare_in_shop.py
└── prepare_landmark_detect.py
```

Then, test_predictor.py gives error:
```
$ python tools/test_predictor.py --config configs/attribute_predict/roi_predictor_resnet_attr.py --checkpoint checkpoint/Predict/resnet/roi/latest.pth

2019-11-13 21:17:13,232 - INFO - Distributed test: False
/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/datasets/Attr_Pred.py:64: UserWarning: loadtxt: Empty input file: "data/Attr_Predict/Anno/test_attr.txt"
  self.labels = np.loadtxt(label_file, dtype=np.float32)
/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/datasets/Attr_Pred.py:77: UserWarning: loadtxt: Empty input file: "data/Attr_Predict/Anno/test_bbox.txt"
  self.bboxes = np.loadtxt(bbox_file, usecols=(0, 1, 2, 3))
/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/datasets/Attr_Pred.py:84: UserWarning: loadtxt: Empty input file: "data/Attr_Predict/Anno/test_landmarks.txt"
  self.landmarks = np.loadtxt(landmark_file)
dataset loaded
model built
load checkpoint from: checkpoint/Predict/resnet/roi/latest.pth
dataloader built
Total
/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/core/evaluation/attr_predict_eval.py:112: RuntimeWarning: invalid value encountered in double_scalars
  len(sorted_recall) - empty)
[Recall] top3 = nan, top5 = nan, top10 = nan
Traceback (most recent call last):
  File "tools/test_predictor.py", line 81, in <module>
    main()
  File "tools/test_predictor.py", line 77, in main
    logger=logger)
  File "/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/apis/test_predictor.py", line 36, in test_predictor
    _non_dist_test(model, dataset, cfg, validate=validate)
  File "/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/apis/test_predictor.py", line 67, in _non_dist_test
    attr_calculator.show_result()
  File "/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/core/evaluation/attr_predict_eval.py", line 160, in show_result
    self.compute_accuracy()
  File "/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/core/evaluation/attr_predict_eval.py", line 147, in compute_accuracy
    top['tp'], top['tn'])
  File "/home/bin/anaconda3/envs/mm/lib/python3.6/site-packages/mmfashion-0.1.0+ad2c911-py3.6.egg/mmfashion/core/evaluation/attr_predict_eval.py", line 141, in compute_one_accuracy
    accuracy[i] = float(tp[i] + tn[i]) / float(self.total)
ZeroDivisionError: float division by zero
```

**Comment by thebeyonder001** [comment]
Were you able to inference the attribute prediction model ?? @gyang274
