### ISSUE TITLE
Incompatibility with newest mmcv version

### ISSUE THREAD

**Issue by hachreak** [open-mmlab/mmfashion#94]
```bash
python tools/train_retriever.py --config configs/retriever_consumer_to_shop/roi_retriever_vgg.py
```

If I try to run training with newest mmcv(-full) version, the script return this error:

```
Traceback (most recent call last):
  File "tools/train_retriever.py", line 85, in <module>
    main()
  File "tools/train_retriever.py", line 81, in main
    logger=logger)
  File "/home/hachreak/projects/mmfashion/mmfashion/apis/train_retriever.py", line 54, in train_retriever
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/hachreak/projects/mmfashion/mmfashion/apis/train_retriever.py", line 79, in _non_dist_train
    cfg.log_level)
  File "/home/hachreak/projects/mmcv/mmcv/runner/epoch_based_runner.py", line 174, in __init__
    super().__init__(*args, **kwargs)
  File "/home/hachreak/projects/mmcv/mmcv/runner/base_runner.py", line 89, in __init__
    raise TypeError(f'logger must be a logging.Logger object, '
TypeError: logger must be a logging.Logger object, but got <class 'str'>
```

**Comment by interestingzhuo** [comment]
I meet the same problem, how did you solve it?
