### ISSUE TITLE
Can't run demo 

### ISSUE THREAD

**Issue by SikandAlex** [open-mmlab/mmfashion#99]
1) Clone project
3) `pythons setup.py install`
2) Download latest.pth model file
3) `python test_attr_predictor.py --checkpoint latest.pth --input test.jpg`

```
Traceback (most recent call last):
  File "test_attr_predictor.py", line 62, in <module>
    main()
  File "test_attr_predictor.py", line 45, in main
    model = build_predictor(cfg.model)
  File "/Users/alex/DeepFashion/mmfashion/mmfashion/models/builder.py", line 87, in build_predictor
    return build(cfg, PREDICTOR)
  File "/Users/alex/DeepFashion/mmfashion/mmfashion/models/builder.py", line 38, in build
    return _build_module(cfg, registry, default_args)
  File "/Users/alex/DeepFashion/mmfashion/mmfashion/models/builder.py", line 30, in _build_module
    return obj_type(**args)
TypeError: __init__() got an unexpected keyword argument 'loss_attr'
```

Python 3.7.7
Torch

**Comment by piggybox** [comment]
Thanks for the info. I've followed the list and fixed the final issue. You have to add that 'loss_attr' to the file in the site-package rather than to the one in the current folder which is github cloned. 

The output I got looks like this
```
The model and loaded state dict do not match exactly

unexpected key in source state_dict: roi_pool.linear.0.weight, roi_pool.linear.0.bias, concat.fc_fusion.weight, concat.fc_fusion.bias

[ Top3 Attribute Prediction ]
sleeve
knit
striped
[ Top5 Attribute Prediction ]
sleeve
knit
striped
stripe
denim
[ Top10 Attribute Prediction ]
sleeve
knit
striped
stripe
denim
leather
lace
maxi
shirt
wash
```

There's still error I hope I can figure out. Not sure if that affects the accuracy of the output.

**Comment by AhmedNageh08** [comment]
@SikandAlex same error , did you find any solution ?

**Comment by AhmedNageh08** [comment]
i found it ..you should add loss_attr in /usr/local/lib/python3.6/dist-packages/mmfashion-0.4.0-py3.6.egg/mmfashion/models/predictor/global_predictor.py  and it'll work

**Comment by Dogacel** [comment]
I think it works but the prediction confidences are pretty low.
